//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mercadito.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MercaditoEntities : DbContext
    {
        public MercaditoEntities()
            : base("name=MercaditoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoriasProducto> CategoriasProductos { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<DatosTarjeta> DatosTarjetas { get; set; }
        public virtual DbSet<DireccionCliente> DireccionClientes { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<Factura> Facturas { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<VentaDetalle> VentaDetalles { get; set; }
        public virtual DbSet<Venta> Ventas { get; set; }
    }
}
